//CREATE A CHAT
export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";

//get my chats
export const GET_MY_CHAT_REQUEST = "GET_MY_CHAT_REQUEST";
export const GET_MY_CHAT_SUCCESS = "GET_MY_CHAT_SUCCESS";
export const GET_MY_CHAT_FAIL = "GET_MY_CHAT_FAIL";