//CREATE A CHAT
export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";


//get all messages from a chats
export const GET_MY_MESSAGE_REQUEST = "GET_MY_MESSAGE_REQUEST";
export const GET_MY_MESSAGE_SUCCESS = "GET_MY_MESSAGE_SUCCESS";
export const GET_MY_MESSAGE_FAIL = "GET_MY_MESSAGE_FAIL";
