//create an order
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

//order details constants
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

//constant to update order after payment
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

//for order history
export const ORDER_MINE_LIST_REQUEST = "ORDER_MINE_LIST_REQUEST"
export const ORDER_MINE_LIST_SUCCESS = "ORDER_MINE_LIST_SUCCESS"
export const ORDER_MINE_LIST_FAIL = "ORDER_MINE_LIST_FAIL"


//for order notification
export const ORDER_NOTIFICATION_REQUEST = "ORDER_NOTIFICATION_REQUEST"
export const ORDER_NOTIFICATION_SUCCESS = "ORDER_NOTIFICATION_SUCCESS"
export const ORDER_NOTIFICATION_FAIL = "ORDER_NOTIFICATION_FAIL"
export const ORDER_NOTIFICATION_RESET = "ORDER_NOTIFICATION_RESET"
