//create product constants
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

//get all products 
export const LIST_OF_PRODUCTS_REQUEST = "LIST_OF_PRODUCTS_REQUEST";
export const LIST_OF_PRODUCTS_SUCCESS = "LIST_OF_PRODUCTS_SUCCESS";
export const LIST_OF_PRODUCTS_FAIL = "LIST_OF_PRODUCTS_FAIL";


//constants to get details of product
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

//constants to get user products
export const USER_PRODUCTS_REQUEST = "USER_PRODUCTS_REQUEST";
export const USER_PRODUCTS_SUCCESS = "USER_PRODUCTS_SUCCESS";
export const USER_PRODUCTS_FAIL = "USER_PRODUCTS_FAIL";

//constants to find a product for update
export const GET_PRODUCT_FOR_UPDATE_REQUEST="GET_PRODUCT_FOR_UPDATE_REQUEST";
export const GET_PRODUCT_FOR_UPDATE_SUCCESS="GET_PRODUCT_FOR_UPDATE_SUCCESS";
export const GET_PRODUCT_FOR_UPDATE_FAIL="GET_PRODUCT_FOR_UPDATE_FAIL";
export const GET_PRODUCT_FOR_UPDATE_RESET = "GET_PRODUCT_FOR_UPDATE_RESET";

//constants to update a user product
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

//constants to update a product that is posted
export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL";

//constants to update a store that is posted
export const UNPOST_PRODUCT_REQUEST = "UNPOST_PRODUCT_REQUEST";
export const UNPOST_PRODUCT_SUCCESS = "UNPOST_PRODUCT_SUCCESS";
export const UNPOST_PRODUCT_FAIL = "UNPOST_PRODUCT_FAIL";

//constants to update a ordered product
export const UPDATE_ORDERED_PRODUCT_REQUEST = "UPDATE_ORDERED_PRODUCT_REQUEST";
export const UPDATE_ORDERED_PRODUCT_SUCCESS = "UPDATE_ORDERED_PRODUCT_SUCCESS";
export const UPDATE_ORDERED_PRODUCT_FAIL = "UPDATE_ORDERED_PRODUCT_FAIL";
export const UPDATE_ORDERED_PRODUCT_RESET = "UPDATE_ORDERED_PRODUCT_RESET";


//find products that are ordered
export const ORDERED_PRODUCTS_REQUEST = "ORDERED_PRODUCTS_REQUEST";
export const ORDERED_PRODUCTS_SUCCESS = "ORDERED_PRODUCTS_SUCCESS";
export const ORDERED_PRODUCTS_FAIL = "ORDERED_PRODUCTS_FAIL";


//find products that are paid
export const UPDATE_PAID_PRODUCTS_REQUEST = "UPDATE_PAID_PRODUCTS_REQUEST";
export const UPDATE_PAID_PRODUCTS_SUCCESS = "UPDATE_PAID_PRODUCTS_SUCCESS";
export const UPDATE_PAID_PRODUCTS_FAIL = "UPDATE_PAID_PRODUCTS_FAIL";
export const UPDATE_PAID_PRODUCTS_RESET = "UPDATE_PAID_PRODUCT_RESET";


//find products that are paid for or sold
export const SOLD_PRODUCTS_REQUEST = "SOLD_PRODUCTS_REQUEST";
export const SOLD_PRODUCTS_SUCCESS = "SOLD_PRODUCTS_SUCCESS";
export const SOLD_PRODUCTS_FAIL = "SOLD_PRODUCTS_FAIL";


//constants to block a product
export const BLOCK_PRODUCT_REQUEST = "BLOCK_PRODUCT_REQUEST";
export const BLOCK_PRODUCT_SUCCESS = "BLOCK_PRODUCT_SUCCESS";
export const BLOCK_PRODUCT_FAIL = "BLOCK_PRODUCT_FAIL";

//constants to unblock a product
export const UNBLOCK_PRODUCT_REQUEST = "UNBLOCK_PRODUCT_REQUEST";
export const UNBLOCK_PRODUCT_SUCCESS = "UNBLOCK_PRODUCT_SUCCESS";
export const UNBLOCK_PRODUCT_FAIL = "UNBLOCK_PRODUCT_FAIL";