//constants to create widthdraw 
export const CREATE_WITHDRAW_REQUEST="CREATE_WITHDRAW_REQUEST"
export const CREATE_WITHDRAW_SUCCESS="CREATE_WITHDRAW_SUCCESS"
export const CREATE_WITHDRAW_FAIL="CREATE_WITHDRAW_FAIL"
export const CREATE_WITHDRAW_RESET="CREATE_WITHDRAW_RESET"

//get widthdrawals
export const GET_WITHDRAWAL_REQUEST="GET_WITHDRAWAL_REQUEST"
export const GET_WITHDRAWAL_SUCCESS="GET_WITHDRAWAL_SUCCESS"
export const GET_WITHDRAWAL_FAIL="GET_WITHDRAWAL_FAIL"